### PR TITLE
Gru september

### PR DESCRIPTION
**Pull request by bpbond**
This includes both the data downloaded from old Gru 2019-09-25 and also (in a second commit) adding three hours to all timestamps.

@lilliehaddock can you check did you start 10:30 AM on the 18th and finish before 4 PM? Or 9:30-3? I'd like to confirm whether machine was on PDT or PST. Thanks.

### CODE REVIEW

**Comment by stephpenn1** [comment]
For `SERC_20190925` file, SP began ~10a and ended exactly at 12pm EDT

**Comment by lilliehaddock** [comment]
For the 18th, I started around ~10:30, yes. That was the day I sent my Panera to the wrong store and started later than expected. I ended around 4pm.

**Comment by lilliehaddock** [comment]
Don't want to merge this yet then, first need to correct times to EST not PDT.

**Comment by bpbond** [comment]
Thanks Lillie!

OK I believe I have changed all the old Gru times from PDT to EST. Should be ready to merge @stephpenn1 but please glance through 1d6b46fa to make sure it makes sense.

**Comment by stephpenn1** [comment]
Don't we want EDT not EST?

**Comment by bpbond** [comment]
In general we'd like to have our instruments on standard time, and leave them there.

**Pull request merged**
