### PR TITLE
Extended Core_placement column

### PR DESCRIPTION
**Pull request by stephpenn1**
Core numbers for control and trenched cores (69-124) were copied from the **Collar** column to the **Core_placement** column to make graphing easier. No core numbers were changed.

### CODE REVIEW

**Comment by bpbond** [comment]
Why does this have conflicts again?

**Comment by stephpenn1** [comment]
I'm not sure? I thought we already fixed whatever conflict there was, anyway.

**Comment by bpbond** [comment]
Ah, fixed it. Not your/anyone's fault.

**Comment by bpbond** [comment]
Thanks @stephpenn1 !

**Pull request merged**
