### PR TITLE
T5 code integration

### PR DESCRIPTION
**Pull request by stephpenn1**
- Code works but `left_join` is adding duplicates when matching T5 to flux data because of multiple same collar measurements on 12/19. (specifically, collars 67 and 48 were both taken twice on accident, and subsequently have two T5 values each) 
- Creates 8 measurements for each collar instead of 4; does not properly match up T5

@bpbond any suggestions would be super helpful! I'm wondering if we should toss the extra flux measurements or create a special case for matching with those collars?

### CODE REVIEW

**Comment by stephpenn1** [comment]
P.S. the merge conflict is because every time I run the `drake` plan I get updated `/drake` files

**Comment by bpbond** [comment]
Whoah, OK, none of those `drake` files should ever have been committed to the repo. Do you mind if I take a look at this branch and push some changes?

**Comment by stephpenn1** [comment]
Oops I'm sorry, some drake files were pushed to master too -.- 

Yes please go ahead!

**Comment by bpbond** [comment]
OK, it was simplest to just merge this. We can now fix, either right on `master` or re-branch first.

**Comment by bpbond** [comment]
@stephpenn1 What's the file/line where the problematic `left_join` happens?

**Pull request merged**
